class FileRepositoryFields:
    HASH = "hash"
    NAME = "name"
    SIZE = "size"
    KIND = "kind"
    MALICIOUS = "malicious"
    SYNC_TIME = "sync_time"
    ARCHITECTURE = "architecture"
    NUM_IMPORTS = "num_imports"
    NUM_EXPORTS = "num_exports"
    STATUS = "status"
    TYPE = "type"
    CREATED_AT = "created_at"
